export const FETCH_DASHBOARD_START = "FETCH_DASHBOARD_START";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_START";
export const FETCH_DASHBOARD_FAIL = 'FETCH_DASHBOARD_FAIL';

export const SET_DASHBOARD_DATA = "SET_DASHBOARD_DATA";

export const FETCH_COVID19_DATA_FROM_API = "FETCH_COVID19_DATA_FROM_API";
export const FETCH_COVID19_DATA_START = "FETCH_COVID19_DATA_START";
export const FETCH_COVID19_DATA_SUCCESS = "FETCH_COVID19_DATA_SUCCESS";
export const FETCH_COVID19_DATA_FAIL = 'FETCH_COVID19_DATA_FAIL';

export const SET_COVID19_DATA = "SET_COVID19_DATA";

export const SELECT_ROW = "SELECT_ROW";
